env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:perfectionist/recommended-natural
  - airbnb
overrides: [
  {
    "files": ["*.jsx", "*.js"]
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures: {
    jsx: true
  }
plugins:
  - react
  - perfectionist
rules:
  no-magic-numbers: [2, { "ignore": [0, 1]}]
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  perfectionist/sort-interfaces: "error"
  perfectionist/sort-array-includes: 0
  perfectionist/sort-objects: 0